server:
  port: 8081
  
  servlet:
    context-path: /sistema-vendas
    
spring:
  application:
    name: Sistema de Vendas
    
  datasource:
    url: jdbc:h2:mem:vendas
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect    
    hibernate:
      ddl-auto: update
    show-sql: true      
    
  h2:
    console:
      enabled: true
      path: /h2-console
